source 'https://rubygems.org'
gem 'rack'
gem 'rake'

# These are printed here for testing environment variable forwarding. We expect the Gemfile
# to be evaluated as code during build, so by printing these here we should see them in the
# build output.
puts "FORWARDED_VARIABLE_0=\"#{ENV['FORWARDED_VARIABLE_0']}\""
puts "FORWARDED_VARIABLE_1=\"#{ENV['FORWARDED_VARIABLE_1']}\""
