test-shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine
  needs: []
  script:
    - shellcheck src/build.sh

.test-build:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  services:
    - "docker:${DOCKER_VERSION}-dind"

test-dockerfile:
  extends: .test-build
  script:
    - cd "$CI_PROJECT_DIR/test/ruby_with_dockerfile"
    - /build/build.sh | tee /tmp/build-output
    - grep 'Building Dockerfile-based application...' /tmp/build-output

# This test is to prevent a regression until https://github.com/docker/engine/pull/339 is out
# See https://gitlab.com/gitlab-org/cluster-integration/auto-build-image/issues/13 for context
test-redhat-registry:
  extends: .test-build
  script:
    - cd "$CI_PROJECT_DIR/test/redhat_registry"
    - /build/build.sh

test-herokuish:
  extends: .test-build
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    - /build/build.sh | tee /tmp/build-output
    - grep 'Building Heroku-based application using gliderlabs/herokuish docker image...' /tmp/build-output

test-cnb:
  extends: .test-build
  variables:
    AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    - /build/build.sh | tee /tmp/build-output
    - grep 'Building Cloud Native Buildpack-based application with builder' /tmp/build-output


test-herokuish-with-build-secrets:
  extends: .test-build
  variables:
    FORWARDED_VARIABLE_0: 'my forwarded variable 0'
    FORWARDED_VARIABLE_1: 'my forwarded variable 1'
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: FORWARDED_VARIABLE_0,FORWARDED_VARIABLE_1
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    # When BuildKit is enabled, docker logs go to stderr by design https://github.com/moby/moby/issues/40031
    - /build/build.sh 2>&1 | tee /tmp/build-output
    - grep 'Building Heroku-based application using gliderlabs/herokuish docker image...' /tmp/build-output
    - grep 'FORWARDED_VARIABLE_0="my forwarded variable 0"' /tmp/build-output
    - grep 'FORWARDED_VARIABLE_1="my forwarded variable 1"' /tmp/build-output

test-cnb-with-build-secrets:
  extends: .test-build
  variables:
    AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
    FORWARDED_VARIABLE_0: 'my forwarded variable 0'
    FORWARDED_VARIABLE_1: 'my forwarded variable 1'
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: FORWARDED_VARIABLE_0,FORWARDED_VARIABLE_1
  script:
    - cd "$CI_PROJECT_DIR/test/ruby"
    # When BuildKit is enabled, docker logs go to stderr by design https://github.com/moby/moby/issues/40031
    - /build/build.sh 2>&1 | tee /tmp/build-output
    - grep 'Building Cloud Native Buildpack-based application with builder' /tmp/build-output
    - grep 'FORWARDED_VARIABLE_0="my forwarded variable 0"' /tmp/build-output
    - grep 'FORWARDED_VARIABLE_1="my forwarded variable 1"' /tmp/build-output

test-herokuish-with-buildpack-url:
  extends: .test-build
  variables:
    BUILDPACK_URL: https://github.com/HashNuke/heroku-buildpack-elixir.git
  script:
    - cd "$CI_PROJECT_DIR/test/elixir"
    - /build/build.sh | tee /tmp/build-output
    - grep 'Building Heroku-based application using gliderlabs/herokuish docker image...' /tmp/build-output
    - grep "Using default config from Elixir buildpack" /tmp/build-output

test-cnb-with-buildpack-url:
  extends: .test-build
  variables:
    AUTO_DEVOPS_BUILD_IMAGE_CNB_ENABLED: "true"
    BUILDPACK_URL: /tmp/elixir_buildpack
  before_script:
    # prepare CNB-compatible elixir buildpack
    - apk add curl
    - mkdir "$BUILDPACK_URL"
    - cd "$BUILDPACK_URL"
    - curl -L https://github.com/heroku/cnb-shim/releases/download/v0.2/cnb-shim-v0.2.tgz | tar xz
    - |
      cat > buildpack.toml << TOML
      api = "0.2"

      [buildpack]
      id = "hashnuke.elixir"
      version = "0.1"
      name = "Elixir"

      [[stacks]]
      id = "heroku-18"
      TOML
    - bin/install buildpack.toml https://buildpack-registry.s3.amazonaws.com/buildpacks/hashnuke/elixir.tgz
  script:
    - cd "$CI_PROJECT_DIR/test/elixir"
    - /build/build.sh | tee /tmp/build-output
    - grep 'Building Cloud Native Buildpack-based application with builder' /tmp/build-output
    - grep "Using default config from Elixir buildpack" /tmp/build-output

test-rspec:
  stage: test
  image: "$BUILD_IMAGE_NAME"
  before_script:
    - gem install --no-document bundler
    - bundle install --without rubocop
  script:
    - bundle exec rspec

test-rubocop:
  stage: test
  image: ruby:2.6
  needs: []
  before_script:
    - gem install bundler
    - bundle install --without test
  script:
    - bundle exec rubocop Gemfile src spec
